name: Azure Terraform Deployment on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan and Apply on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Set Azure credentials as environment variables
        run: |
          echo "Setting Azure environment variables"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_WORKSPACE: "my-azure-workspace"  # Replace with your Terraform Cloud workspace name
          TF_TOKEN: ${{ secrets.TF_API_TOKEN }}  # Your Terraform Cloud API token

      - name: Terraform Apply (Manual Approval Required)
        run: terraform apply -auto-approve=false
        env:
          TF_WORKSPACE: "my-azure-workspace"
          TF_TOKEN: ${{ secrets.TF_API_TOKEN }}
